# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\hf_work\python_work\ConsleDataProcess\DataAnalyze.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataAnalyze(object):
    def setupUi(self, DataAnalyze):
        DataAnalyze.setObjectName("DataAnalyze")
        DataAnalyze.resize(1282, 693)
        self.centralwidget = QtWidgets.QWidget(DataAnalyze)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_FileDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FileDir.setGeometry(QtCore.QRect(162, 20, 361, 21))
        self.lineEdit_FileDir.setReadOnly(True)
        self.lineEdit_FileDir.setObjectName("lineEdit_FileDir")
        self.DirButton = QtWidgets.QPushButton(self.centralwidget)
        self.DirButton.setGeometry(QtCore.QRect(530, 17, 31, 28))
        self.DirButton.setObjectName("DirButton")
        self.label_FileDir = QtWidgets.QLabel(self.centralwidget)
        self.label_FileDir.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_FileDir.setObjectName("label_FileDir")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(980, 70, 281, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_Process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Process.setGeometry(QtCore.QRect(880, 70, 93, 28))
        self.pushButton_Process.setObjectName("pushButton_Process")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(200, 100, 1071, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1041, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 1061, 531))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit2.setGeometry(QtCore.QRect(0, 0, 1061, 531))
        self.textEdit2.setObjectName("textEdit2")
        self.tabWidget.addTab(self.tab_3, "")
        self.listWidget_KeyName = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_KeyName.setGeometry(QtCore.QRect(10, 100, 181, 571))
        self.listWidget_KeyName.setObjectName("listWidget_KeyName")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 70, 301, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_CanID = QtWidgets.QLabel(self.widget)
        self.label_CanID.setTextFormat(QtCore.Qt.AutoText)
        self.label_CanID.setObjectName("label_CanID")
        self.horizontalLayout_2.addWidget(self.label_CanID)
        self.lineEdit_Key = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Key.setObjectName("lineEdit_Key")
        self.horizontalLayout_2.addWidget(self.lineEdit_Key)
        self.comboBox_Type = QtWidgets.QComboBox(self.widget)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.horizontalLayout_2.addWidget(self.comboBox_Type)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(370, 70, 181, 23))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_value = QtWidgets.QLabel(self.widget1)
        self.label_value.setTextFormat(QtCore.Qt.AutoText)
        self.label_value.setObjectName("label_value")
        self.horizontalLayout.addWidget(self.label_value)
        self.lineEdit_value = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_value.setObjectName("lineEdit_value")
        self.horizontalLayout.addWidget(self.lineEdit_value)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(596, 71, 211, 23))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_x = QtWidgets.QLabel(self.widget2)
        self.label_x.setTextFormat(QtCore.Qt.AutoText)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_3.addWidget(self.label_x)
        self.lineEdit_value2 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_value2.setObjectName("lineEdit_value2")
        self.horizontalLayout_3.addWidget(self.lineEdit_value2)
        DataAnalyze.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DataAnalyze)
        self.statusbar.setObjectName("statusbar")
        DataAnalyze.setStatusBar(self.statusbar)

        self.retranslateUi(DataAnalyze)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DataAnalyze)

    def retranslateUi(self, DataAnalyze):
        _translate = QtCore.QCoreApplication.translate
        DataAnalyze.setWindowTitle(_translate("DataAnalyze", "DataAnalyze"))
        self.DirButton.setText(_translate("DataAnalyze", "..."))
        self.label_FileDir.setText(_translate("DataAnalyze", "选择数据文件路径"))
        self.pushButton_Process.setText(_translate("DataAnalyze", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DataAnalyze", "折线图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DataAnalyze", "按值筛选结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DataAnalyze", "按横坐标筛选结果"))
        self.label_CanID.setText(_translate("DataAnalyze", "KEY："))
        self.label_value.setText(_translate("DataAnalyze", "值：大于"))
        self.label_x.setText(_translate("DataAnalyze", "横坐标：大于"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataAnalyze = QtWidgets.QMainWindow()
    ui = Ui_DataAnalyze()
    ui.setupUi(DataAnalyze)
    DataAnalyze.show()
    sys.exit(app.exec_())
